site_name: Programación Modular
site_description: Apunts de Programació Modular - Curs 2025-2026
site_author: Sergio Soriano Reyes
docs_dir: md
site_dir: docs

theme:
  name: material
  language: ca
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Canvia a mode fosc
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Canvia a mode clar
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - toc.integrate

plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: Imprimir / Descarregar PDF
      add_print_site_banner: true
      print_site_banner_template: md/templates/custom_banner.html
      add_table_of_contents: true
      toc_title: Taula de continguts
      add_cover_page: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - attr_list

nav:
  - Inicio: index.md
